Repository: plone.tiles


Branch: refs/heads/master
Date: 2016-09-12T08:57:29+03:00
Author: Asko Soukka (datakurre) <asko.soukka@iki.fi>
Commit: https://github.com/plone/plone.tiles/commit/64887368193eec5c8ac951a746899a6334e509b8

Fix issue where collective.cover was broken, because internal changes in default data managers

Files changed:
M plone/tiles/data.py

diff --git a/plone/tiles/data.py b/plone/tiles/data.py
index cb6cce3..7975184 100644
--- a/plone/tiles/data.py
+++ b/plone/tiles/data.py
@@ -57,6 +57,10 @@ def __init__(self, tile):
         else:
             self.key = str(tile.id)
 
+    @property
+    def annotations(self):  # BBB for < 0.7.0 support
+        return self.stoage
+
     def get(self):
         # use explicitly set data (saved as annotation on the request)
         if self.key in self.storage:
@@ -116,6 +120,10 @@ def __init__(self, tile):
         else:
             self.key = str(tile.id)
 
+    @property
+    def annotations(self):  # BBB for < 0.7.0 support
+        return self.stoage
+
     def _get_default_request_data(self):
         # If we don't have a schema, just take the request
         if self.tileType is None or self.tileType.schema is None:


